import { Castle } from "./types";

export const Areas = [
  "hiroshima",
  "okayama",
  "shimane",
  "tottori",
  "yamaguchi",
  "fukui",
  "ishikawa",
  "toyama",
  "chiba",
  "gunma",
  "ibaraki",
  "kanagawa",
  "saitama",
  "tochigi",
  "tokyo",
  "hyogo",
  "kyoto",
  "nara",
  "osaka",
  "shiga",
  "wakayama",
  "nagano",
  "nigata",
  "yamanashi",
  "fukuoka",
  "kagoshima",
  "kumamoto",
  "miyazaki",
  "nagasaki",
  "oita",
  "okinawa",
  "saga",
  "ehime",
  "kagawa",
  "kouchi",
  "tokushima",
  "akita",
  "aomori",
  "fukushima",
  "hokkaido",
  "iwate",
  "miyagi",
  "yamagata",
  "aichi",
  "gifu",
  "mie",
  "shizuoka",
] as const;
export type AreaType = typeof Prefs[number];

export const Regions = [
  "chugoku",
  "hokuriku",
  "kanto",
  "kinki",
  "koushinnetsu",
  "kyusyu",
  "shikoku",
  "tohoku",
  "tokai",
] as const;
export type RegionType = typeof Prefs[number];

export const Prefs = [
  "hiroshima",
  "okayama",
  "shimane",
  "tottori",
  "yamaguchi",
  "fukui",
  "ishikawa",
  "toyama",
  "chiba",
  "gunma",
  "ibaraki",
  "kanagawa",
  "saitama",
  "tochigi",
  "tokyo",
  "hyogo",
  "kyoto",
  "nara",
  "osaka",
  "shiga",
  "wakayama",
  "nagano",
  "nigata",
  "yamanashi",
  "fukuoka",
  "kagoshima",
  "kumamoto",
  "miyazaki",
  "nagasaki",
  "oita",
  "okinawa",
  "saga",
  "ehime",
  "kagawa",
  "kouchi",
  "tokushima",
  "akita",
  "aomori",
  "fukushima",
  "hokkaido",
  "iwate",
  "miyagi",
  "yamagata",
  "aichi",
  "gifu",
  "mie",
  "shizuoka",
] as const;
export type PrefType = typeof Prefs[number];

type AreasFromPrefType = {
  [key in PrefType]: AreaType[];
};
export const AreasFromPref: AreasFromPrefType = {
  hiroshima: ["hiroshima"],
  okayama: ["okayama"],
  shimane: ["shimane"],
  tottori: ["tottori"],
  yamaguchi: ["yamaguchi"],
  fukui: ["fukui"],
  ishikawa: ["ishikawa"],
  toyama: ["toyama"],
  chiba: ["chiba"],
  gunma: ["gunma"],
  ibaraki: ["ibaraki"],
  kanagawa: ["kanagawa"],
  saitama: ["saitama"],
  tochigi: ["tochigi"],
  tokyo: ["tokyo"],
  hyogo: ["hyogo"],
  kyoto: ["kyoto"],
  nara: ["nara"],
  osaka: ["osaka"],
  shiga: ["shiga"],
  wakayama: ["wakayama"],
  nagano: ["nagano"],
  nigata: ["nigata"],
  yamanashi: ["yamanashi"],
  fukuoka: ["fukuoka"],
  kagoshima: ["kagoshima"],
  kumamoto: ["kumamoto"],
  miyazaki: ["miyazaki"],
  nagasaki: ["nagasaki"],
  oita: ["oita"],
  okinawa: ["okinawa"],
  saga: ["saga"],
  ehime: ["ehime"],
  kagawa: ["kagawa"],
  kouchi: ["kouchi"],
  tokushima: ["tokushima"],
  akita: ["akita"],
  aomori: ["aomori"],
  fukushima: ["fukushima"],
  hokkaido: ["hokkaido"],
  iwate: ["iwate"],
  miyagi: ["miyagi"],
  yamagata: ["yamagata"],
  aichi: ["aichi"],
  gifu: ["gifu"],
  mie: ["mie"],
  shizuoka: ["shizuoka"],
};

export type JPCastlesType = {
  [key in PrefType]: {
    [key in AreaType]?: Castle[];
  };
};
