import { Prefectures } from "./types/types";

export const prefectures: Prefectures = {
  hokkaido: {
    name: "北海道",
    region: "tohoku",
    area: ["douou", "dounan", "douhoku", "doutou"],
    path: "/data/tohoku/hokkaido/",
  },
  aomori: {
    name: "青森県",
    region: "tohoku",
    area: ["aomori"],
    path: "/data/tohoku/aomori/",
  },
  iwate: {
    name: "岩手県",
    region: "tohoku",
    area: ["iwate"],
    path: "/data/tohoku/iwate/",
  },
  miyagi: {
    name: "宮城県",
    region: "tohoku",
    area: ["miyagi"],
    path: "/data/tohoku/miyagi/",
  },
  akita: {
    name: "秋田県",
    region: "tohoku",
    area: ["akita"],
    path: "/data/tohoku/akita/",
  },
  yamagata: {
    name: "山形県",
    region: "tohoku",
    area: ["yamagata"],
    path: "/data/tohoku/yamagata/",
  },
  fukushima: {
    name: "福島県",
    region: "tohoku",
    area: ["fukushima"],
    path: "/data/tohoku/fukushima/",
  },
  ibaraki: {
    name: "茨城県",
    region: "kanto",
    area: ["kenhoku", "kenou", "rokkou", "kennan"],
    path: "/data/kanto/ibaraki/",
  },
  tochigi: {
    name: "栃木県",
    region: "kanto",
    area: ["kenou", "kennan", "kenhoku"],
    path: "/data/kanto/tochigi/",
  },
  gunma: {
    name: "群馬県",
    region: "kanto",
    area: ["chubu", "seibu", "tone", "azuma", "toubu"],
    path: "/data/kanto/gunma/",
  },
  saitama: {
    name: "埼玉県",
    region: "kanto",
    area: [
      "kitaadachi",
      "iruma",
      "hiki",
      "chichibu",
      "kodama",
      "osato",
      "kitasaitama",
      "minamisaitama",
      "kitakatsushika",
    ],
    path: "/data/kanto/saitama/",
  },
  chiba: {
    name: "千葉県",
    region: "kanto",
    area: [
      "tokatsu",
      "inba",
      "chiba",
      "katori",
      "kaisou",
      "sanmu",
      "chousei",
      "isumi",
      "kimitsu",
      "awa",
    ],
    path: "/data/kanto/chiba/",
  },
  tokyo: {
    name: "東京都",
    region: "kanto",
    area: ["kubu", "tama", "tosyoubu"],
    path: "/data/kanto/tokyo/",
  },
  kanagawa: {
    name: "神奈川県",
    region: "kanto",
    area: [
      "yokohama",
      "kawasaki",
      "yokosukamiura",
      "kenou",
      "syonan",
      "kensei",
    ],
    path: "/data/kanto/kanagawa/",
  },
  nigata: {
    name: "新潟県",
    region: "koushinetsu",
    area: ["joetsu", "chuetsu", "kaetsu", "sado"],
    path: "/data/koushinetsu/nigata/",
  },
  yamanashi: {
    name: "山梨県",
    region: "koushinetsu",
    area: ["kuninaka", "gunnai"],
    path: "/data/koushinetsu/yamanashi/",
  },
  nagano: {
    name: "長野県",
    region: "koushinetsu",
    area: ["hokushin", "toushin", "chushin", "nanshin"],
    path: "/data/koushinetsu/nagano/",
  },
  toyama: {
    name: "富山県",
    region: "hokuriku",
    area: ["gotou", "gosei"],
    path: "/data/hokuriku/toyama/",
  },
  ishikawa: {
    name: "石川県",
    region: "hokuriku",
    area: ["noto", "kaga"],
    path: "/data/hokuriku/ishikawa/",
  },
  fukui: {
    name: "福井県",
    region: "hokuriku",
    area: ["echizen", "wakasa"],
    path: "/data/hokuriku/fukui/",
  },
  gifu: {
    name: "岐阜県",
    region: "tokai",
    area: ["hida", "mino"],
    path: "/data/tokai/gifu/",
  },
  shizuoka: {
    name: "静岡県",
    region: "tokai",
    area: ["izu", "toubu", "chubu", "seibu"],
    path: "/data/tokai/shizuoka/",
  },
  aichi: {
    name: "愛知県",
    region: "tokai",
    area: ["higashimikawa", "nishimikawa", "owari"],
    path: "/data/tokai/aichi/",
  },
  mie: {
    name: "三重県",
    region: "tokai",
    area: ["hokusei", "iga", "chusei", "nansei", "higashikisyu"],
    path: "/data/tokai/mie/",
  },
  shiga: {
    name: "滋賀県",
    region: "kinki",
    area: ["konan", "kotou", "kohoku", "kosei"],
    path: "/data/kinki/shiga/",
  },
  kyoto: {
    name: "京都府",
    region: "kinki",
    area: ["tango", "chutan", "nantan", "kyoto", "yamashiro"],
    path: "/data/kinki/kyoto/",
  },
  osaka: {
    name: "大阪府",
    region: "kinki",
    area: [
      "osaka",
      "mishima",
      "toyono",
      "senboku",
      "sennan",
      "minamikawachi",
      "nakakawachi",
      "kitakawachi",
    ],
    path: "/data/kinki/osaka/",
  },
  hyogo: {
    name: "兵庫県",
    region: "kinki",
    area: [
      "koube",
      "hanshinminami",
      "hanshinkita",
      "higashiharima",
      "kitaharima",
      "nakaharima",
      "nishiharima",
      "tanba",
      "tajima",
      "awaji",
    ],
    path: "/data/kinki/hyogo/",
  },
  nara: {
    name: "奈良県",
    region: "kinki",
    area: ["hokubu", "nanbu"],
    path: "/data/kinki/nara/",
  },
  wakayama: {
    name: "和歌山県",
    region: "kinki",
    area: ["kihoku", "kinan", "kichu"],
    path: "/data/kinki/wakayama/",
  },
  tottori: {
    name: "鳥取県",
    region: "chugoku",
    area: ["toubu", "chubu", "nanbu"],
    path: "/data/chugoku/tottori/",
  },
  shimane: {
    name: "島根県",
    region: "chugoku",
    area: ["izumo", "iwami", "oki"],
    path: "/data/chugoku/shimane/",
  },
  okayama: {
    name: "岡山県",
    region: "chugoku",
    area: ["bizen", "bicchu", "mimasaka"],
    path: "/data/chugoku/okayama/",
  },
  hiroshima: {
    name: "広島県",
    region: "chugoku",
    area: ["aki", "bingo"],
    path: "/data/chugoku/hiroshima/",
  },
  yamaguchi: {
    name: "山口県",
    region: "chugoku",
    area: ["ganryu", "syunan", "sanbou", "asa", "houkan", "chohoku"],
    path: "/data/chugoku/yamaguchi/",
  },
  tokushima: {
    name: "徳島県",
    region: "shikoku",
    area: ["toubu", "nanbu", "seibu"],
    path: "/data/shikoku/tokushima/",
  },
  kagawa: {
    name: "香川県",
    region: "shikoku",
    area: ["tousan", "seisan"],
    path: "/data/shikoku/kagawa/",
  },
  ehime: {
    name: "愛媛県",
    region: "shikoku",
    area: ["touyo", "chuyo", "nanyo"],
    path: "/data/shikoku/ehime/",
  },
  kouchi: {
    name: "高知県",
    region: "shikoku",
    area: ["kouban", "hata", "reihoku", "monobegawa", "niyodogawa", "aki"],
    path: "/data/shikoku/kouchi/",
  },
  fukuoka: {
    name: "福岡県",
    region: "kyusyu",
    area: ["fukuoka", "kitakyusyu", "chikugo", "chikuhou"],
    path: "/data/kyusyu/fukuoka/",
  },
  saga: {
    name: "佐賀県",
    region: "kyusyu",
    area: ["sanshin", "sashiro", "kitou", "karamatsu", "isei"],
    path: "/data/kyusyu/saga/",
  },
  nagasaki: {
    name: "長崎県",
    region: "kyusyu",
    area: [
      "nagasaki",
      "kenhoku",
      "kenou",
      "shimabara",
      "gotou",
      "iki",
      "tsushima",
    ],
    path: "/data/kyusyu/nagasaki/",
  },
  kumamoto: {
    name: "熊本県",
    region: "kyusyu",
    area: [
      "tamana",
      "kamoto",
      "kikuchi",
      "aso",
      "kumamoto",
      "uki",
      "kamimashiki",
      "yatsushiro",
      "ashikita",
      "kuma",
      "amakusa",
    ],
    path: "/data/kyusyu/kumamoto/",
  },
  oita: {
    name: "大分県",
    region: "kyusyu",
    path: "/data/kyusyu/oita/",
    area: ["chibu", "toubu", "hokubu", "seibu", "nanbu", "houhi"],
  },
  miyazaki: {
    name: "宮崎県",
    region: "kyusyu",
    area: ["kenhoku", "kenou", "kensei", "kennan"],
    path: "/data/kyusyu/miyazaki/",
  },
  kagoshima: {
    name: "鹿児島県",
    region: "kyusyu",
    area: ["nansatsu", "hokusatsu", "airaisa", "osumi", "kumage", "osima"],
    path: "/data/kyusyu/kagoshima/",
  },
  okinawa: {
    name: "沖縄県",
    region: "kyusyu",
    area: ["hokubu", "chubu", "nanbu", "miyakoyaeyama"],
    path: "/data/kyusyu/okinawa/",
  },
};
